server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Gzip
  gzip on;
  gzip_types text/plain text/css application/json application/javascript;

  # Cache assets estáticos
  location ~* \.(js|css|png|jpg|svg|ico|woff2)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # SPA fallback — qualquer rota vai para o index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}